/**
 * Core domain types for EdgeFuzz.
 * All modules import from here — keeps cross-module contracts stable.
 */

// ---------------------------------------------------------------------------
// OpenAPI / Schema types
// ---------------------------------------------------------------------------

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';

export interface ParsedParameter {
  name: string;
  in: 'query' | 'header' | 'path' | 'cookie';
  required: boolean;
  schema: JsonSchema;
}

export interface ParsedEndpoint {
  method: HttpMethod;
  path: string;
  operationId?: string;
  summary?: string;
  parameters: ParsedParameter[];
  requestBody?: {
    required: boolean;
    contentType: string;
    schema: JsonSchema;
  };
}

export interface ParsedSpec {
  baseUrl: string;
  specSource: string; // URL or file path used to load the spec
  endpoints: ParsedEndpoint[];
}

// ---------------------------------------------------------------------------
// JSON Schema (simplified subset we handle)
// ---------------------------------------------------------------------------

export interface JsonSchema {
  type?: string | string[];
  format?: string;
  properties?: Record<string, JsonSchema>;
  items?: JsonSchema;
  required?: string[];
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  enum?: unknown[];
  nullable?: boolean;
  // OpenAPI 3.1 nullable representation
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  allOf?: JsonSchema[];
  $ref?: string;
  additionalProperties?: boolean | JsonSchema;
}

// ---------------------------------------------------------------------------
// Mutation types
// ---------------------------------------------------------------------------

/** A single adversarial payload variant to be sent to an endpoint */
export interface MutatedRequest {
  endpoint: ParsedEndpoint;
  /** Unique identifier for the mutation rule that produced this payload */
  mutationId: string;
  /** Human-readable description of what this mutation is testing */
  mutationLabel: string;
  /** Category bucket for grouping in reports */
  mutationCategory: MutationCategory;
  /**
   * Source of this mutation:
   *  'static'  — generated by hardcoded rule engine (zero LLM cost, always runs)
   *  'llm'     — generated by LLM semantic analysis (requires API key, opt-in)
   */
  mutationSource: MutationSource;
  /** Final URL with path params substituted */
  url: string;
  method: HttpMethod;
  headers: Record<string, string>;
  /** Query params (for GET/DELETE etc.) */
  queryParams?: Record<string, string>;
  /** JSON body (for POST/PUT/PATCH) */
  body?: unknown;
}

export type MutationSource = 'static' | 'llm';

export type MutationCategory =
  | 'type-boundary'
  | 'structural'
  | 'encoding'
  | 'format'
  | 'security'
  | 'semantic'; // LLM-generated business-logic / semantic mutations

// ---------------------------------------------------------------------------
// LLM Semantic Mutation types (Phase A)
// ---------------------------------------------------------------------------

/**
 * A single semantic mutation proposed by the LLM.
 * The LLM returns these as structured JSON — never free text —
 * so they can be safely injected into the fuzzing pipeline.
 */
export interface SemanticMutation {
  /** Short human-readable label, e.g. "Expired coupon code" */
  label: string;
  /** LLM's reasoning for why this might crash the server */
  reasoning: string;
  /** Request body payload (for POST/PUT/PATCH endpoints) */
  body?: Record<string, unknown>;
  /** Query parameter overrides (for GET/DELETE endpoints) */
  queryParams?: Record<string, string>;
}

/**
 * Structured JSON schema the LLM must conform to when generating mutations.
 * Used with OpenAI's response_format: { type: 'json_schema' } or
 * Anthropic's tool-use structured output.
 */
export interface SemanticMutationResponse {
  mutations: SemanticMutation[];
}

// ---------------------------------------------------------------------------
// LLM Crash Triage types (Phase C)
// ---------------------------------------------------------------------------

/**
 * Known root-cause categories the LLM triage assigns to each crash.
 * Using a closed enum forces the LLM to pick a canonical label rather
 * than hallucinating arbitrary strings, making reports consistent.
 */
export type CrashRootCause =
  | 'integer-overflow'
  | 'null-pointer'
  | 'type-coercion'
  | 'unhandled-exception'
  | 'sql-error'
  | 'nosql-error'
  | 'encoding-error'
  | 'validation-missing'
  | 'timeout-hang'
  | 'memory-error'
  | 'auth-bypass'
  | 'path-traversal'
  | 'injection'
  | 'schema-mismatch'
  | 'unknown';

/**
 * Triage result for a single crash, produced by the LLM.
 * Always structured JSON — never free text injected into logic.
 */
export interface CrashTriageResult {
  /** The crash id this triage result corresponds to */
  crashId: string;
  /** Canonical root-cause category */
  rootCause: CrashRootCause;
  /**
   * Confidence score 0.0–1.0.
   * < 0.4 = low confidence (environment artifact, not a real bug)
   * 0.4–0.7 = medium confidence (likely real, needs verification)
   * > 0.7 = high confidence (clear bug)
   */
  confidence: number;
  /** 1-2 sentence plain-English explanation of why this crash occurred */
  notes: string;
  /**
   * If this crash appears to be the same root cause as another crash,
   * set this to that crash's id. The first occurrence is the canonical one.
   */
  duplicateOf?: string;
  /**
   * LLM can upgrade or downgrade severity based on reading the stack trace.
   * Omit to keep the static classifier's severity.
   */
  severityOverride?: CrashSeverity;
}

// ---------------------------------------------------------------------------
// Execution / result types
// ---------------------------------------------------------------------------

export interface RequestResult {
  request: MutatedRequest;
  statusCode: number;
  responseBody: string;
  latencyMs: number;
  /** True if the connection timed out entirely (server hang) */
  timedOut: boolean;
  /** True if a network-level error occurred before getting a response */
  networkError: boolean;
  networkErrorMessage?: string;
  /** Node.js / undici error code (e.g. 'ECONNREFUSED', 'UND_ERR_HEADERS_TIMEOUT') */
  networkErrorCode?: string;
}

// ---------------------------------------------------------------------------
// Crash / finding types
// ---------------------------------------------------------------------------

export type CrashSeverity = 'critical' | 'high' | 'medium' | 'low';

export interface CrashFinding {
  /** Dedup key — same endpoint + mutation rule = same crash */
  id: string;
  /** Static severity from the rule classifier */
  severity: CrashSeverity;
  endpoint: ParsedEndpoint;
  mutationId: string;
  mutationLabel: string;
  mutationCategory: MutationCategory;
  /** Whether this mutation was generated by static rules or LLM */
  mutationSource: MutationSource;
  statusCode: number;
  responseBody: string;
  latencyMs: number;
  timedOut: boolean;
  /** True if a network-level error caused the crash (server died mid-request) */
  networkError: boolean;
  /** The exact payload that triggered the crash */
  triggeringPayload: unknown;
  /** Ready-to-run curl command that reproduces the crash */
  curlReproducer: string;

  // ---- LLM Triage fields (Phase C) — populated after fuzzing completes ----
  /** LLM-assigned root cause category */
  rootCause?: CrashRootCause;
  /** LLM confidence score 0.0–1.0 */
  confidence?: number;
  /** LLM explanation of why this crash occurred */
  triageNotes?: string;
  /** id of another CrashFinding with the same root cause (dedup signal) */
  duplicateOf?: string;
  /** LLM-overridden severity (may differ from static classifier) */
  llmSeverity?: CrashSeverity;

  /** @deprecated Use triageNotes + rootCause instead */
  llmFixSuggestion?: string;
}

// ---------------------------------------------------------------------------
// Report types
// ---------------------------------------------------------------------------

export interface FuzzReport {
  version: '1';
  generatedAt: string; // ISO 8601
  target: string;
  specSource: string;
  /** Whether LLM features were active during this run */
  llmEnabled: boolean;
  summary: {
    totalRequests: number;
    totalEndpoints: number;
    /** Total unique crashes (post-dedup) */
    totalCrashes: number;
    /** Crashes that are LLM-confirmed duplicates (same root cause) */
    totalDuplicates: number;
    /** How many mutations were LLM-generated (0 if --llm-mutations not set) */
    llmMutations: number;
    durationMs: number;
    requestsPerSecond: number;
  };
  crashes: CrashFinding[];
}

// ---------------------------------------------------------------------------
// Config / options types
// ---------------------------------------------------------------------------

export interface EdgeFuzzConfig {
  /** Target base URL (e.g. http://localhost:8080) */
  targetUrl: string;
  /** Path or URL to OpenAPI spec; if omitted, auto-discovery is attempted */
  specPath?: string;
  /** Max concurrent in-flight HTTP requests */
  concurrency: number;
  /** Per-request timeout in milliseconds */
  timeoutMs: number;
  /** Where to write the JSON report; false = don't write */
  reportPath: string | false;
  /** Disable TUI and output plain text (useful for CI) */
  ci: boolean;
  /** LLM provider to use */
  llmProvider?: 'openai' | 'anthropic';
  /** Override LLM model name */
  llmModel?: string;
  /**
   * Custom base URL for the LLM API endpoint.
   * Use this to point at a LiteLLM proxy, local Ollama, or any OpenAI-compatible server.
   * Reads EDGEFUZZ_LLM_BASE_URL from env when not set via --llm-base-url.
   */
  llmBaseUrl?: string;
  /**
   * Enable LLM-generated semantic mutations (Phase A).
   * Requires OPENAI_API_KEY or ANTHROPIC_API_KEY.
   * Default: false (static rules always run regardless).
   */
  llmMutations: boolean;
  /**
   * Enable LLM crash triage (Phase C).
   * Requires OPENAI_API_KEY or ANTHROPIC_API_KEY.
   * Default: true when a key is present (passive, no extra input needed).
   */
  llmTriage: boolean;
  /** Custom request headers to include in all fuzzing requests */
  headers: Record<string, string>;
  /** Only fuzz endpoints matching these path prefixes */
  includePaths?: string[];
  /** Skip endpoints matching these path prefixes */
  excludePaths?: string[];
}

// ---------------------------------------------------------------------------
// Progress event types (used by TUI / CI reporter)
// ---------------------------------------------------------------------------

export type ProgressEvent =
  | { type: 'start'; totalRequests: number; totalEndpoints: number; llmEnabled: boolean }
  | { type: 'llm_mutations_generating'; endpointCount: number }
  | { type: 'llm_mutations_ready'; count: number }
  | { type: 'request_done'; result: RequestResult }
  | { type: 'crash_found'; crash: CrashFinding }
  | { type: 'triage_start'; crashCount: number }
  | { type: 'triage_done'; crashes: CrashFinding[] }
  | { type: 'done'; report: FuzzReport };
