/**
 * Core domain types for EdgeFuzz.
 * All modules import from here — keeps cross-module contracts stable.
 */

// ---------------------------------------------------------------------------
// OpenAPI / Schema types
// ---------------------------------------------------------------------------

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';

export interface ParsedParameter {
  name: string;
  in: 'query' | 'header' | 'path' | 'cookie';
  required: boolean;
  schema: JsonSchema;
}

export interface ParsedEndpoint {
  method: HttpMethod;
  path: string;
  operationId?: string;
  summary?: string;
  parameters: ParsedParameter[];
  requestBody?: {
    required: boolean;
    contentType: string;
    schema: JsonSchema;
  };
  /**
   * Response schemas keyed by HTTP status code string (e.g. "200", "201", "default").
   * Used for response schema validation after each request.
   */
  responseSchemas?: Record<string, JsonSchema>;
}

export interface ParsedSpec {
  baseUrl: string;
  specSource: string; // URL or file path used to load the spec
  endpoints: ParsedEndpoint[];
}

// ---------------------------------------------------------------------------
// JSON Schema (simplified subset we handle)
// ---------------------------------------------------------------------------

export interface JsonSchema {
  type?: string | string[];
  format?: string;
  properties?: Record<string, JsonSchema>;
  items?: JsonSchema;
  required?: string[];
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  enum?: unknown[];
  nullable?: boolean;
  // OpenAPI 3.1 nullable representation
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  allOf?: JsonSchema[];
  $ref?: string;
  additionalProperties?: boolean | JsonSchema;
}

// ---------------------------------------------------------------------------
// Mutation types
// ---------------------------------------------------------------------------

/** A single adversarial payload variant to be sent to an endpoint */
export interface MutatedRequest {
  endpoint: ParsedEndpoint;
  /** Unique identifier for the mutation rule that produced this payload */
  mutationId: string;
  /** Human-readable description of what this mutation is testing */
  mutationLabel: string;
  /** Category bucket for grouping in reports */
  mutationCategory: MutationCategory;
  /**
   * Source of this mutation:
   *  'static'  — generated by hardcoded rule engine (zero LLM cost, always runs)
   *  'llm'     — generated by LLM semantic analysis (requires API key, opt-in)
   */
  mutationSource: MutationSource;
  /** Final URL with path params substituted */
  url: string;
  method: HttpMethod;
  headers: Record<string, string>;
  /** Query params (for GET/DELETE etc.) */
  queryParams?: Record<string, string>;
  /** JSON body (for POST/PUT/PATCH) */
  body?: unknown;
}

export type MutationSource = 'static' | 'llm';

export type MutationCategory =
  | 'type-boundary'
  | 'structural'
  | 'encoding'
  | 'format'
  | 'security'
  | 'semantic'; // LLM-generated business-logic / semantic mutations

// ---------------------------------------------------------------------------
// LLM Semantic Mutation types (Phase A)
// ---------------------------------------------------------------------------

/**
 * A single semantic mutation proposed by the LLM.
 * The LLM returns these as structured JSON — never free text —
 * so they can be safely injected into the fuzzing pipeline.
 */
export interface SemanticMutation {
  /** Short human-readable label, e.g. "Expired coupon code" */
  label: string;
  /** LLM's reasoning for why this might crash the server */
  reasoning: string;
  /** Request body payload (for POST/PUT/PATCH endpoints) */
  body?: Record<string, unknown>;
  /** Query parameter overrides (for GET/DELETE endpoints) */
  queryParams?: Record<string, string>;
}

/**
 * Structured JSON schema the LLM must conform to when generating mutations.
 * Used with OpenAI's response_format: { type: 'json_schema' } or
 * Anthropic's tool-use structured output.
 */
export interface SemanticMutationResponse {
  mutations: SemanticMutation[];
}

// ---------------------------------------------------------------------------
// Execution / result types
// ---------------------------------------------------------------------------

export interface RequestResult {
  request: MutatedRequest;
  statusCode: number;
  responseBody: string;
  latencyMs: number;
  /** True if the connection timed out entirely (server hang) */
  timedOut: boolean;
  /** True if a network-level error occurred before getting a response */
  networkError: boolean;
  networkErrorMessage?: string;
  /** Node.js / undici error code (e.g. 'ECONNREFUSED', 'UND_ERR_HEADERS_TIMEOUT') */
  networkErrorCode?: string;
}

// ---------------------------------------------------------------------------
// Crash / finding types
// ---------------------------------------------------------------------------

export type CrashSeverity = 'critical' | 'high' | 'medium' | 'low';

/**
 * Root cause labels assigned by the LLM triage engine (Phase C).
 * This is a closed enum — the LLM is constrained to these values only.
 */
export type CrashRootCause =
  | 'integer-overflow'
  | 'null-pointer'
  | 'type-coercion'
  | 'unhandled-exception'
  | 'sql-error'
  | 'nosql-error'
  | 'encoding-error'
  | 'validation-missing'
  | 'timeout-hang'
  | 'memory-error'
  | 'auth-bypass'
  | 'path-traversal'
  | 'injection'
  | 'schema-mismatch'
  | 'unknown';

/**
 * Intermediate triage result returned by the LLM for one crash.
 * Applied in-place to the CrashFinding via applyTriageResults().
 */
export interface CrashTriageResult {
  crashId: string;
  rootCause: CrashRootCause;
  confidence: number; // 0.0–1.0
  notes: string;
  duplicateOf?: string; // id of another crash with the same root cause
  severityOverride?: CrashSeverity;
}

export interface CrashFinding {
  /** Dedup key — same endpoint + mutation rule = same crash */
  id: string;
  /** Static severity from the rule classifier */
  severity: CrashSeverity;
  endpoint: ParsedEndpoint;
  mutationId: string;
  mutationLabel: string;
  mutationCategory: MutationCategory;
  /** Whether this mutation was generated by static rules or LLM */
  mutationSource: MutationSource;
  statusCode: number;
  responseBody: string;
  latencyMs: number;
  timedOut: boolean;
  /** True if a network-level error caused the crash (server died mid-request) */
  networkError: boolean;
  /** The exact payload that triggered the crash */
  triggeringPayload: unknown;
  /** Ready-to-run curl command that reproduces the crash */
  curlReproducer: string;

  // --- LLM triage fields (populated only when --triage is used) ---
  /** LLM-classified root cause */
  rootCause?: CrashRootCause;
  /** LLM confidence score for the root cause (0.0–1.0) */
  confidence?: number;
  /** 1-2 sentence LLM explanation of the crash */
  triageNotes?: string;
  /** ID of another crash that shares the same underlying bug */
  duplicateOf?: string;
  /** LLM-overridden severity (when response body reveals more than static rules could) */
  llmSeverity?: CrashSeverity;
}

// ---------------------------------------------------------------------------
// Response mismatch / contract violation types
// ---------------------------------------------------------------------------

export type MismatchKind =
  | 'missing-required-field'   // response body omits a field marked required in the spec
  | 'wrong-type'               // field present but wrong JSON type vs spec
  | 'error-body-leaked'        // non-2xx body contains stack trace / internal details
  | 'undocumented-status'      // server returned a status code not in the spec's responses
  | 'empty-success-body';      // 200/201 returned empty body when schema expects an object

/**
 * A response that violates the API contract documented in the OpenAPI spec.
 * These are not crashes (no 500) but indicate bugs or data leakage.
 */
export interface ResponseMismatch {
  /** Unique ID for deduplication (hash of endpoint key + mismatch kind + field) */
  id: string;
  kind: MismatchKind;
  severity: CrashSeverity;
  endpoint: ParsedEndpoint;
  mutationId: string;
  mutationLabel: string;
  statusCode: number;
  /** Human-readable description of what was expected vs. what was received */
  message: string;
  /** The field path that was wrong, e.g. "user.email" (undefined for whole-body mismatches) */
  fieldPath?: string;
  /** The actual JSON value received (may be undefined/missing) */
  actualValue?: unknown;
  /** The expected JSON type from the spec */
  expectedType?: string;
  /** Excerpt of the response body (for error-body-leaked cases) */
  responseExcerpt?: string;
  /** Ready-to-run curl command that reproduces the mismatch */
  curlReproducer: string;
}

// ---------------------------------------------------------------------------
// Report types
// ---------------------------------------------------------------------------

export interface FuzzReport {
  version: '1';
  generatedAt: string; // ISO 8601
  target: string;
  specSource: string;
  /** Whether LLM features were active during this run */
  llmEnabled: boolean;
  summary: {
    totalRequests: number;
    totalEndpoints: number;
    /** Total unique crashes (post-dedup) */
    totalCrashes: number;
    /** Total response contract violations detected */
    totalMismatches: number;
    /** How many mutations were LLM-generated (0 if --llm-mutations not set) */
    llmMutations: number;
    /**
     * Number of crashes identified as duplicates of another crash by LLM triage.
     * Only present when --triage was used (undefined otherwise).
     */
    totalDuplicates?: number;
    durationMs: number;
    requestsPerSecond: number;
  };
  crashes: CrashFinding[];
  /** Response contract violations (wrong types, missing fields, data leakage) */
  mismatches: ResponseMismatch[];
}

// ---------------------------------------------------------------------------
// Config / options types
// ---------------------------------------------------------------------------

export interface EdgeFuzzConfig {
  /** Target base URL (e.g. http://localhost:8080) */
  targetUrl: string;
  /** Path or URL to OpenAPI spec; if omitted, auto-discovery is attempted */
  specPath?: string;
  /** Max concurrent in-flight HTTP requests */
  concurrency: number;
  /** Per-request timeout in milliseconds */
  timeoutMs: number;
  /** Where to write the JSON report; false = don't write */
  reportPath: string | false;
  /** Disable TUI and output plain text (useful for CI) */
  ci: boolean;
  /** LLM provider to use */
  llmProvider?: 'openai' | 'anthropic';
  /** Override LLM model name */
  llmModel?: string;
  /**
   * Custom base URL for the LLM API endpoint.
   * Use this to point at a LiteLLM proxy, local Ollama, or any OpenAI-compatible server.
   * Reads EDGEFUZZ_LLM_BASE_URL from env when not set via --llm-base-url.
   */
  llmBaseUrl?: string;
  /**
   * Enable LLM-generated semantic mutations (Phase A).
   * Requires OPENAI_API_KEY or ANTHROPIC_API_KEY.
   * Default: false (static rules always run regardless).
   */
  llmMutations: boolean;
  /** Custom request headers to include in all fuzzing requests */
  headers: Record<string, string>;
  /** Only fuzz endpoints matching these path prefixes */
  includePaths?: string[];
  /** Skip endpoints matching these path prefixes */
  excludePaths?: string[];
  /**
   * Shell command to run to obtain a bearer token.
   * Output must be either a plain string (the token) or JSON with a "token" field.
   * Re-run automatically on 401 responses (once per run) to handle token expiry.
   * Example: 'curl -s -X POST https://auth.example.com/token -d "client_id=..." | jq -r .access_token'
   */
  authCommand?: string;
  /**
   * Skip TLS certificate verification.
   * Use for dev/staging servers with self-signed certificates.
   * Default: false (certificates are verified).
   */
  tlsInsecure?: boolean;
  /**
   * Delay between requests in milliseconds.
   * Useful for APIs with rate limiting. Applied per-request before execution.
   * Default: 0 (no delay).
   */
  requestDelay?: number;
  /**
   * Disable response schema validation.
   * When true, mismatches are not collected and the response validator is skipped entirely.
   * Use --no-response-validation for crash-only mode (faster, lower noise).
   * Default: false (validation enabled).
   */
  skipResponseValidation?: boolean;
  /**
   * Enable LLM crash triage (Phase C) after fuzzing completes.
   * Sends all deduplicated crashes to the LLM in batches of 20 for:
   *  - Root cause classification (closed enum, not free text)
   *  - Cross-crash duplicate detection
   *  - Optional severity override when response body reveals more than static rules
   * Default: false (triage disabled — opt-in only via --triage flag).
   * Requires OPENAI_API_KEY or ANTHROPIC_API_KEY (same as --llm-mutations).
   */
  llmTriage?: boolean;
}

// ---------------------------------------------------------------------------
// Progress event types (used by TUI / CI reporter)
// ---------------------------------------------------------------------------

export type ProgressEvent =
  | { type: 'start'; totalRequests: number; totalEndpoints: number; llmEnabled: boolean }
  | { type: 'llm_mutations_generating'; endpointCount: number }
  | { type: 'llm_mutations_ready'; count: number }
  | { type: 'request_done'; result: RequestResult }
  | { type: 'crash_found'; crash: CrashFinding }
  | { type: 'mismatch_found'; mismatch: ResponseMismatch }
  | { type: 'triage_start'; crashCount: number }
  | { type: 'triage_done'; duplicateCount: number }
  | { type: 'done'; report: FuzzReport };
